version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Copenhagen
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Copenhagen
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Copenhagen
