---
version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - varnamelen
  settings:
    exhaustive:
      default-signifies-exhaustive: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/ms
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal/ms
      - third_party$
      - builtin$
      - examples$
